version: 2.1

executors:
  app-executor:
    docker:
      - image: circleci/node:16.10
    # Directory where all circleci image will be added default is ~/project
    working_directory: ~/repo

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  # ? For yarn
  # - run:
  #     name: Install yarn
  #     command: npm install -g yarn
  # - run:
  #     name: Install dependencies
  #     command: yarn install
  - &save-cache
    save_cache:
      key: app-{{ checksum "package.json" }}
      paths:
        - node_modules

# orbs:
#   node: circleci/node@4.7

# jobs:
#   build-and-test:
#     docker:
#       - image: cimg/node:16.10
#     steps:
#       - checkout
#       - node/install-packages:
#           # If you are using yarn, change the line below from "npm" to "yarn"
#           pkg-manager: npm
#       - run:
#           name: Run tests
#           command: npm test

jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache

  test:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run tests
          command: npm test

  deploy-to-heroku:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - run:
          name: Deploy to heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]
            then
              git push https://heroku.$HEROKU_API_KEY@git.heroku.com/my-house-prod.git ${CIRCLE_BRANCH}:main -f
            elif [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              git push https://heroku.$HEROKU_API_KEY@git.heroku.com/my-house-dev.git ${CIRCLE_BRANCH}:main -f
            else
              git push https://heroku.$HEROKU_API_KEY@git.heroku.com/my-house-dev.git ${CIRCLE_BRANCH}:main -f
            fi

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - main
      - deploy-to-heroku:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - main
